### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by malikmajai** [MrJacob12/StringProgressBar#2]
----- Installing 'pip install StringProgressBar' -----
Requirement already satisfied: pip in c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\site-packages (22.0.4)
Collecting install
  Using cached install-1.3.5-py3-none-any.whl (3.2 kB)
Collecting StringProgressBar
  Using cached StringProgressBar-1.1.1.tar.gz (4.0 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [1 lines of output]
  ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
Encountered error while generating package metadata.
See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
----- Failed to install 'pip install StringProgressBar' -----

**Comment by MrJacob12** [comment]
Whats your python and pip version? 
I done two tests on Windows 11 (pip 22.0.4 and python 3.8.8) and Raspberry OS (pip 20.3.4 and Python 3.9.2).
You can try to [purge cache](https://stackoverflow.com/questions/9510474/pip-uses-incorrect-cached-package-version-instead-of-the-user-specified-version) and install again
<img width="770" alt="image" src="https://user-images.githubusercontent.com/46843555/165754745-e2fbe680-f71a-4774-b2b0-46ff225c2360.png">
---
<img width="814" alt="image" src="https://user-images.githubusercontent.com/46843555/165755097-075e6773-b213-4534-9528-fe9732f43ca2.png">

**Comment by malikmajai** [comment]
> ## Whats your python and pip version?
> I done two tests on Windows 11 (pip 22.0.4 and python 3.8.8) and Raspberry OS (pip 20.3.4 and Python 3.9.2).
> You can try to [purge cache](https://stackoverflow.com/questions/9510474/pip-uses-incorrect-cached-package-version-instead-of-the-user-specified-version) and install again
> <img alt="image" width="770" src="https://user-images.githubusercontent.com/46843555/165754745-e2fbe680-f71a-4774-b2b0-46ff225c2360.png">
> <img alt="image" width="814" src="https://user-images.githubusercontent.com/46843555/165755097-075e6773-b213-4534-9528-fe9732f43ca2.png">

Thanks, after updating setup tools, it worked :)
